//! # D-Bus interface proxy for: `org.shadowblip.Input.Source.HIDRawDevice`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/shadowblip/InputPlumber/devices/source/hidraw0' from service 'org.shadowblip.InputPlumber' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.shadowblip.Input.Source.HIDRawDevice",
    default_service = "org.shadowblip.InputPlumber",
    default_path = "/org/shadowblip/InputPlumber/devices/source/hidraw0"
)]
pub trait HIDRawDevice {
    /// DevPath property
    #[zbus(property)]
    fn dev_path(&self) -> zbus::Result<String>;

    /// IdProduct property
    #[zbus(property)]
    fn id_product(&self) -> zbus::Result<String>;

    /// IdVendor property
    #[zbus(property)]
    fn id_vendor(&self) -> zbus::Result<String>;

    /// InterfaceNumber property
    #[zbus(property)]
    fn interface_number(&self) -> zbus::Result<i32>;

    /// Manufacturer property
    #[zbus(property)]
    fn manufacturer(&self) -> zbus::Result<String>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// Product property
    #[zbus(property)]
    fn product(&self) -> zbus::Result<String>;

    /// SerialNumber property
    #[zbus(property)]
    fn serial_number(&self) -> zbus::Result<String>;

    /// SysfsPath property
    #[zbus(property)]
    fn sysfs_path(&self) -> zbus::Result<String>;
}
