//! # D-Bus interface proxy for: `org.shadowblip.CPU.Core`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/shadowblip/Performance/CPU/Core0' from service 'org.shadowblip.PowerStation' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.shadowblip.CPU.Core",
    default_service = "org.shadowblip.PowerStation",
    default_path = "/org/shadowblip/Performance/CPU/Core0"
)]
pub trait Core {
    /// CoreId property
    #[zbus(property)]
    fn core_id(&self) -> zbus::Result<u32>;

    /// Number property
    #[zbus(property)]
    fn number(&self) -> zbus::Result<u32>;

    /// Online property
    #[zbus(property)]
    fn online(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_online(&self, value: bool) -> zbus::Result<()>;
}
