#!/usr/bin/bash
set -eu

if [[ $EUID -ne 0 ]]; then
  exec pkexec --disable-internal-agent "$0" "$HOME" "$@"
fi

ARCH=$(uname -m)
USER_HOME="$1"
UPDATE_PATH="${USER_HOME}/.local/share/opengamepadui/updates/opengamepad-ui.${ARCH}"
setcap 'cap_sys_nice=eip' "${UPDATE_PATH}"
