#!/bin/bash

set -eu

if [[ $EUID -ne 0 ]]; then
  exec pkexec --disable-internal-agent "$0" "$@"
fi

## CPU Generics
cpuBoost(){
 state=$1
  /usr/bin/echo $state > /sys/devices/system/cpu/cpufreq/boost
}

cpuToggle(){
 num=$1
 state=$2
 /usr/bin/echo $state > /sys/bus/cpu/devices/cpu${num}/online
}

smtToggle(){
 state=$1
  /usr/bin/echo $state > /sys/devices/system/cpu/smt/control
}

## AMD APU
amdGpuClock(){
  min_clk=$1
  max_clk=$2
  card=$3
  /usr/bin/echo "s 0 ${min_clk}" > /sys/class/drm/${card}/device/pp_od_clk_voltage
  /usr/bin/echo "s 1 ${max_clk}" > /sys/class/drm/${card}/device/pp_od_clk_voltage
  /usr/bin/echo "c" > /sys/class/drm/${card}/device/pp_od_clk_voltage
}

ryzenadjLong(){
  cmd=$1
  val=$2
  /usr/bin/ryzenadj $cmd $val
}

ryzenadjShort(){
  cmd=$1
  /usr/bin/ryzenadj $cmd
}

setAmdPerfLevelValue() { # set power_dpm_force_performace_level mode
  mode=$1
  card=$2
  /usr/bin/echo $mode > /sys/class/drm/${card}/device/power_dpm_force_performance_level
}

setAmdPerfLevelWrite() { # set power_dpm_force_performace_level write
  card=$1
  /usr/bin/chmod a+w /sys/class/drm/${card}/device/power_dpm_force_performance_level
}

setThermalPolicy(){
  mode=$1
  /usr/bin/echo $mode > /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
}

## INTEL iGPU
# Package TDP Control
setRapl(){
  power_type=$1
  val=$2
  /usr/bin/echo $val > /sys/class/powercap/intel-rapl/intel-rapl:0/${power_type}
}

# GPU Frquency Control
intelGpuClock(){
  min_clk=$1
  max_clk=$2
  card=$3
  /usr/bin/echo $min_clk > /sys/class/drm/${card}/gt_min_freq_mhz
  /usr/bin/echo $max_clk > /sys/class/drm/${card}gt_max_freq_mhz
}

## CPU Generics
if [[ $1 == "cpuBoost" ]]; then
  cpuBoost $2

elif [[ $1 == "cpuToggle" ]]; then
  cpuToggle $2 $3

elif [[ $1 == "smtToggle" ]]; then
  smtToggle $2

## AMD APU's
elif [[ $1 == "amdGpuClock" ]]; then
  amdGpuClock $2 $3 $4

elif [[ $1 == "pdfpl" ]]; then
  if [[ $2 == "write" ]]; then
    setAmdPerfLevelWrite $3
  else
    setAmdPerfLevelValue $2 $3
  fi

elif [[ $1 == "ryzenadj" ]]; then
  if [[ $# > 2 ]]; then
    ryzenadjLong $2 $3
  else
    ryzenadjShort $2
  fi

## Intel iGPU's
elif [[ $1 == "setRapl" ]]; then
  setRapl $2 $3

elif [[ $1 == "intelGpuClock" ]]; then
  intelGpuClock $2 $3 $4

## ASUS Specific
elif [[ $1 == "setThermalPolicy" ]]; then
  setThermalPolicy $2
fi
