#!/bin/bash

set -eu

if [[ $EUID -ne 0 ]]; then
  exec pkexec --disable-internal-agent "$0" "$@"
fi

## CPU Generics
cpuBoost(){
  /usr/bin/echo $1 > /sys/devices/system/cpu/cpufreq/boost
}

cpuPower(){
  /usr/bin/cpupower $1 $2 $3
}

cpuToggle(){
 /usr/bin/echo $2 > /sys/bus/cpu/devices/cpu${1}/online
}

smtToggle(){
  /usr/bin/echo $1 > /sys/devices/system/cpu/smt/control
}

## AMD APU
amdGpuClock(){
  /usr/bin/echo "s 0 ${1}" > /sys/class/drm/card0/device/pp_od_clk_voltage
  /usr/bin/echo "s 1 ${2}" > /sys/class/drm/card0/device/pp_od_clk_voltage
  /usr/bin/echo "c" > /sys/class/drm/card0/device/pp_od_clk_voltage
}

ryzenadjLong(){
  /usr/bin/ryzenadj $1 $2
}

ryzenadjShort(){
  /usr/bin/ryzenadj $1
}

setAmdPerfLevelValue() { # set power_dpm_force_performace_level mode
  /usr/bin/echo $1 > /sys/class/drm/card0/device/power_dpm_force_performance_level
}

setAmdPerfLevelWrite() { # set power_dpm_force_performace_level write
  /usr/bin/chmod a+w /sys/class/drm/card0/device/power_dpm_force_performance_level
}

setThermalPolicy(){
  /usr/bin/echo $1 > /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
}

## INTEL iGPU
setRapl(){ #TDP Control
  /usr/bin/echo $1 > /sys/class/powercap/intel-rapl/intel-rapl:0/gt_min_freq_mhz
  /usr/bin/echo $2 > /sys/class/powercap/intel-rapl/intel-rapl:0/gt_max_freq_mhz
}

intelGpuClock(){
  /usr/bin/echo $2 > /sys/class/drm/card0/${1}
}

## CPU Generics
if [[ $1 == "cpuBoost" ]]; then
  cpuBoost $2

elif [[ $1 == "cpuPower" ]]; then
  cpuPower $2 $3 $4

elif [[ $1 == "cpuToggle" ]]; then
  cpuToggle $2 $3

elif [[ $1 == "smtToggle" ]]; then
  smtToggle $2

## AMD APU's
elif [[ $1 == "amdGpuClock" ]]; then
  amdGpuClock $2 $3

elif [[ $1 == "pdfpl" ]]; then
  if [[ $2 == "write" ]]; then
    setAmdPerfLevelWrite
  else
    setAmdPerfLevelValue $2
  fi

elif [[ $1 == "ryzenadj" ]]; then
  if [[ $# > 2 ]]; then
    ryzenadjLong $2 $3
  else
    ryzenadjShort $2
  fi

## Intel iGPU's
elif [[ $1 == "setRapl" ]]; then
  setRapl $2 $3

elif [[ $1 == "intelGpuClock" ]]; then
  intelGpuClock $2 $3

## ASUS Specific
elif [[ $1 == "setThermalPolicy" ]]; then
  setThermalPolicy $2
fi
