#include "device.h"
#include "event.h"

#include <fcntl.h>
#include <iostream>
#include <libevdev/libevdev-uinput.h>
#include <libevdev/libevdev.h>
#include <linux/input.h>
#include <stdio.h>
#include <unistd.h>

#include "godot_cpp/classes/global_constants.hpp"
#include "godot_cpp/core/class_db.hpp"
#include "godot_cpp/core/memory.hpp"
#include "godot_cpp/variant/string.hpp"
#include <godot_cpp/variant/utility_functions.hpp>

// References:
// https://github.com/ShadowBlip/HandyGCCS/blob/main/usr/share/handygccs/scripts/handycon.py
// https://github.com/gvalkov/python-evdev/blob/2dd6ce6364bb67eedb209f6aa0bace0c18a3a40a/evdev/device.py#L1

namespace evdev {
using godot::D_METHOD;
using godot::ERR_CANT_OPEN;
using godot::ERR_DOES_NOT_EXIST;
using godot::String;

InputDevice::InputDevice(){};
InputDevice::~InputDevice() {
  // Close our file descriptors
  close();
};

// Opens the given device
int InputDevice::open(String device) {
  // Certain operations are only possible when opened in read-write mode
  fd = ::open(device.ascii().get_data(), O_RDWR | O_NONBLOCK);
  if (fd < 0) {
    fd = ::open(device.ascii().get_data(), O_RDONLY | O_NONBLOCK);
    if (fd < 0) {
      godot::UtilityFunctions::push_error("Unable to open input device: ",
                                          device);
      return ERR_CANT_OPEN;
    }
  }
  int code = libevdev_new_from_fd(fd, &dev);
  if (code < 0) {
    ::close(fd);
    godot::UtilityFunctions::push_error("Failed to init libevdev: ", device);
    return ERR_CANT_OPEN;
  }
  path = device;

  return godot::OK;
};

// Close the device
int InputDevice::close() {
  int code = 0;
  if (fd > 0) {
    code = ::close(fd);
  }
  if (code < 0) {
    return godot::ERR_CANT_OPEN;
  }
  fd = 0;
  libevdev_free(dev);
  return code;
};

// Grabs the device for exclusive access
int InputDevice::grab(bool mode) {
  if (!is_open()) {
    return ERR_DOES_NOT_EXIST;
  }
  int code = 0;
  if (mode) {
    code = libevdev_grab(dev, LIBEVDEV_GRAB);
    if (code == 0) {
      grabbed = true;
    }
  } else {
    code = libevdev_grab(dev, LIBEVDEV_UNGRAB);
    if (code == 0) {
      grabbed = false;
    }
    grabbed = false;
  }
  return code;
}

// Gets the device name
String InputDevice::get_name() {
  if (!is_open()) {
    return "";
  }
  const char *name_str = libevdev_get_name(dev);
  return String(name_str);
}

// Return path
String InputDevice::get_path() { return path; };

// Device info functions
int InputDevice::get_bustype() {
  if (!is_open()) {
    return ERR_DOES_NOT_EXIST;
  }
  return libevdev_get_id_bustype(dev);
}

int InputDevice::get_vendor() {
  if (!is_open()) {
    return ERR_DOES_NOT_EXIST;
  }
  return libevdev_get_id_vendor(dev);
}

int InputDevice::get_product() {
  if (!is_open()) {
    return ERR_DOES_NOT_EXIST;
  }
  return libevdev_get_id_product(dev);
}

int InputDevice::get_version() {
  if (!is_open()) {
    return ERR_DOES_NOT_EXIST;
  }
  return libevdev_get_id_version(dev);
}

String InputDevice::get_phys() {
  if (!is_open()) {
    return "";
  }
  const char *phys = libevdev_get_phys(dev);
  return String(phys);
}

bool InputDevice::has_event_type(unsigned int event_type) {
  if (!is_open()) {
    return false;
  }
  return libevdev_has_event_type(dev, event_type);
}

bool InputDevice::has_event_code(unsigned int event_type,
                                 unsigned int event_code) {
  if (!is_open()) {
    return false;
  }

  return libevdev_has_event_code(dev, event_type, event_code);
}

// Get the next event from the device
// https://www.freedesktop.org/software/libevdev/doc/latest/group__events.html#gabb96c864e836c0b98788f4ab771c3a76
InputDeviceEvent *InputDevice::next_event() {
  if (!is_open()) {
    return nullptr;
  }
  struct input_event ev;
  int code = 0;
  code = libevdev_next_event(dev, LIBEVDEV_READ_FLAG_NORMAL, &ev);
  if (code > 0) {
    return nullptr;
  }
  InputDeviceEvent *event = memnew(InputDeviceEvent());
  event->code = ev.code;
  event->type = ev.type;
  event->value = ev.value;
  return event;
}

// Returns whether the device is currently open
bool InputDevice::is_open() { return fd > 0; };
bool InputDevice::is_grabbed() { return grabbed; };

// Register the methods with Godot
void InputDevice::_bind_methods() {
  // Properties

  // Methods
  godot::ClassDB::bind_method(D_METHOD("open", "dev"), &InputDevice::open);
  godot::ClassDB::bind_method(D_METHOD("close"), &InputDevice::close);
  godot::ClassDB::bind_method(D_METHOD("grab", "mode"), &InputDevice::grab);
  godot::ClassDB::bind_method(D_METHOD("get_path"), &InputDevice::get_path);
  godot::ClassDB::bind_method(D_METHOD("get_name"), &InputDevice::get_name);
  godot::ClassDB::bind_method(D_METHOD("get_bustype"),
                              &InputDevice::get_bustype);
  godot::ClassDB::bind_method(D_METHOD("get_vendor"), &InputDevice::get_vendor);
  godot::ClassDB::bind_method(D_METHOD("get_product"),
                              &InputDevice::get_product);
  godot::ClassDB::bind_method(D_METHOD("get_version"),
                              &InputDevice::get_version);
  godot::ClassDB::bind_method(D_METHOD("get_phys"), &InputDevice::get_phys);
  godot::ClassDB::bind_method(D_METHOD("has_event_type", "event_type"),
                              &InputDevice::has_event_type);
  godot::ClassDB::bind_method(
      D_METHOD("has_event_code", "event_type", "event_code"),
      &InputDevice::has_event_code);
  godot::ClassDB::bind_method(D_METHOD("next_event"), &InputDevice::next_event);
  godot::ClassDB::bind_method(D_METHOD("is_open"), &InputDevice::is_open);
  godot::ClassDB::bind_method(D_METHOD("is_grabbed"), &InputDevice::is_grabbed);

  // Static methods

  // Constants
  BIND_CONSTANT(INPUT_PROP_POINTER);
  BIND_CONSTANT(INPUT_PROP_DIRECT);
  BIND_CONSTANT(INPUT_PROP_BUTTONPAD);
  BIND_CONSTANT(INPUT_PROP_SEMI_MT);
  BIND_CONSTANT(INPUT_PROP_TOPBUTTONPAD);
  BIND_CONSTANT(INPUT_PROP_POINTING_STICK);
  BIND_CONSTANT(INPUT_PROP_ACCELEROMETER);
  BIND_CONSTANT(INPUT_PROP_MAX);
  BIND_CONSTANT(INPUT_PROP_CNT);
  BIND_CONSTANT(EV_SYN);
  BIND_CONSTANT(EV_KEY);
  BIND_CONSTANT(EV_REL);
  BIND_CONSTANT(EV_ABS);
  BIND_CONSTANT(EV_MSC);
  BIND_CONSTANT(EV_SW);
  BIND_CONSTANT(EV_LED);
  BIND_CONSTANT(EV_SND);
  BIND_CONSTANT(EV_REP);
  BIND_CONSTANT(EV_FF);
  BIND_CONSTANT(EV_PWR);
  BIND_CONSTANT(EV_FF_STATUS);
  BIND_CONSTANT(EV_MAX);
  BIND_CONSTANT(EV_CNT);
  BIND_CONSTANT(SYN_REPORT);
  BIND_CONSTANT(SYN_CONFIG);
  BIND_CONSTANT(SYN_MT_REPORT);
  BIND_CONSTANT(SYN_DROPPED);
  BIND_CONSTANT(SYN_MAX);
  BIND_CONSTANT(SYN_CNT);
  BIND_CONSTANT(KEY_RESERVED);
  BIND_CONSTANT(KEY_ESC);
  BIND_CONSTANT(KEY_1);
  BIND_CONSTANT(KEY_2);
  BIND_CONSTANT(KEY_3);
  BIND_CONSTANT(KEY_4);
  BIND_CONSTANT(KEY_5);
  BIND_CONSTANT(KEY_6);
  BIND_CONSTANT(KEY_7);
  BIND_CONSTANT(KEY_8);
  BIND_CONSTANT(KEY_9);
  BIND_CONSTANT(KEY_0);
  BIND_CONSTANT(KEY_MINUS);
  BIND_CONSTANT(KEY_EQUAL);
  BIND_CONSTANT(KEY_BACKSPACE);
  BIND_CONSTANT(KEY_TAB);
  BIND_CONSTANT(KEY_Q);
  BIND_CONSTANT(KEY_W);
  BIND_CONSTANT(KEY_E);
  BIND_CONSTANT(KEY_R);
  BIND_CONSTANT(KEY_T);
  BIND_CONSTANT(KEY_Y);
  BIND_CONSTANT(KEY_U);
  BIND_CONSTANT(KEY_I);
  BIND_CONSTANT(KEY_O);
  BIND_CONSTANT(KEY_P);
  BIND_CONSTANT(KEY_LEFTBRACE);
  BIND_CONSTANT(KEY_RIGHTBRACE);
  BIND_CONSTANT(KEY_ENTER);
  BIND_CONSTANT(KEY_LEFTCTRL);
  BIND_CONSTANT(KEY_A);
  BIND_CONSTANT(KEY_S);
  BIND_CONSTANT(KEY_D);
  BIND_CONSTANT(KEY_F);
  BIND_CONSTANT(KEY_G);
  BIND_CONSTANT(KEY_H);
  BIND_CONSTANT(KEY_J);
  BIND_CONSTANT(KEY_K);
  BIND_CONSTANT(KEY_L);
  BIND_CONSTANT(KEY_SEMICOLON);
  BIND_CONSTANT(KEY_APOSTROPHE);
  BIND_CONSTANT(KEY_GRAVE);
  BIND_CONSTANT(KEY_LEFTSHIFT);
  BIND_CONSTANT(KEY_BACKSLASH);
  BIND_CONSTANT(KEY_Z);
  BIND_CONSTANT(KEY_X);
  BIND_CONSTANT(KEY_C);
  BIND_CONSTANT(KEY_V);
  BIND_CONSTANT(KEY_B);
  BIND_CONSTANT(KEY_N);
  BIND_CONSTANT(KEY_M);
  BIND_CONSTANT(KEY_COMMA);
  BIND_CONSTANT(KEY_DOT);
  BIND_CONSTANT(KEY_SLASH);
  BIND_CONSTANT(KEY_RIGHTSHIFT);
  BIND_CONSTANT(KEY_KPASTERISK);
  BIND_CONSTANT(KEY_LEFTALT);
  BIND_CONSTANT(KEY_SPACE);
  BIND_CONSTANT(KEY_CAPSLOCK);
  BIND_CONSTANT(KEY_F1);
  BIND_CONSTANT(KEY_F2);
  BIND_CONSTANT(KEY_F3);
  BIND_CONSTANT(KEY_F4);
  BIND_CONSTANT(KEY_F5);
  BIND_CONSTANT(KEY_F6);
  BIND_CONSTANT(KEY_F7);
  BIND_CONSTANT(KEY_F8);
  BIND_CONSTANT(KEY_F9);
  BIND_CONSTANT(KEY_F10);
  BIND_CONSTANT(KEY_NUMLOCK);
  BIND_CONSTANT(KEY_SCROLLLOCK);
  BIND_CONSTANT(KEY_KP7);
  BIND_CONSTANT(KEY_KP8);
  BIND_CONSTANT(KEY_KP9);
  BIND_CONSTANT(KEY_KPMINUS);
  BIND_CONSTANT(KEY_KP4);
  BIND_CONSTANT(KEY_KP5);
  BIND_CONSTANT(KEY_KP6);
  BIND_CONSTANT(KEY_KPPLUS);
  BIND_CONSTANT(KEY_KP1);
  BIND_CONSTANT(KEY_KP2);
  BIND_CONSTANT(KEY_KP3);
  BIND_CONSTANT(KEY_KP0);
  BIND_CONSTANT(KEY_KPDOT);
  BIND_CONSTANT(KEY_ZENKAKUHANKAKU);
  BIND_CONSTANT(KEY_102ND);
  BIND_CONSTANT(KEY_F11);
  BIND_CONSTANT(KEY_F12);
  BIND_CONSTANT(KEY_RO);
  BIND_CONSTANT(KEY_KATAKANA);
  BIND_CONSTANT(KEY_HIRAGANA);
  BIND_CONSTANT(KEY_HENKAN);
  BIND_CONSTANT(KEY_KATAKANAHIRAGANA);
  BIND_CONSTANT(KEY_MUHENKAN);
  BIND_CONSTANT(KEY_KPJPCOMMA);
  BIND_CONSTANT(KEY_KPENTER);
  BIND_CONSTANT(KEY_RIGHTCTRL);
  BIND_CONSTANT(KEY_KPSLASH);
  BIND_CONSTANT(KEY_SYSRQ);
  BIND_CONSTANT(KEY_RIGHTALT);
  BIND_CONSTANT(KEY_LINEFEED);
  BIND_CONSTANT(KEY_HOME);
  BIND_CONSTANT(KEY_UP);
  BIND_CONSTANT(KEY_PAGEUP);
  BIND_CONSTANT(KEY_LEFT);
  BIND_CONSTANT(KEY_RIGHT);
  BIND_CONSTANT(KEY_END);
  BIND_CONSTANT(KEY_DOWN);
  BIND_CONSTANT(KEY_PAGEDOWN);
  BIND_CONSTANT(KEY_INSERT);
  BIND_CONSTANT(KEY_DELETE);
  BIND_CONSTANT(KEY_MACRO);
  BIND_CONSTANT(KEY_MUTE);
  BIND_CONSTANT(KEY_VOLUMEDOWN);
  BIND_CONSTANT(KEY_VOLUMEUP);
  BIND_CONSTANT(KEY_POWER);
  BIND_CONSTANT(KEY_KPEQUAL);
  BIND_CONSTANT(KEY_KPPLUSMINUS);
  BIND_CONSTANT(KEY_PAUSE);
  BIND_CONSTANT(KEY_SCALE);
  BIND_CONSTANT(KEY_KPCOMMA);
  BIND_CONSTANT(KEY_HANGEUL);
  BIND_CONSTANT(KEY_HANGUEL);
  BIND_CONSTANT(KEY_HANJA);
  BIND_CONSTANT(KEY_YEN);
  BIND_CONSTANT(KEY_LEFTMETA);
  BIND_CONSTANT(KEY_RIGHTMETA);
  BIND_CONSTANT(KEY_COMPOSE);
  BIND_CONSTANT(KEY_STOP);
  BIND_CONSTANT(KEY_AGAIN);
  BIND_CONSTANT(KEY_PROPS);
  BIND_CONSTANT(KEY_UNDO);
  BIND_CONSTANT(KEY_FRONT);
  BIND_CONSTANT(KEY_COPY);
  BIND_CONSTANT(KEY_OPEN);
  BIND_CONSTANT(KEY_PASTE);
  BIND_CONSTANT(KEY_FIND);
  BIND_CONSTANT(KEY_CUT);
  BIND_CONSTANT(KEY_HELP);
  BIND_CONSTANT(KEY_MENU);
  BIND_CONSTANT(KEY_CALC);
  BIND_CONSTANT(KEY_SETUP);
  BIND_CONSTANT(KEY_SLEEP);
  BIND_CONSTANT(KEY_WAKEUP);
  BIND_CONSTANT(KEY_FILE);
  BIND_CONSTANT(KEY_SENDFILE);
  BIND_CONSTANT(KEY_DELETEFILE);
  BIND_CONSTANT(KEY_XFER);
  BIND_CONSTANT(KEY_PROG1);
  BIND_CONSTANT(KEY_PROG2);
  BIND_CONSTANT(KEY_WWW);
  BIND_CONSTANT(KEY_MSDOS);
  BIND_CONSTANT(KEY_COFFEE);
  BIND_CONSTANT(KEY_SCREENLOCK);
  BIND_CONSTANT(KEY_ROTATE_DISPLAY);
  BIND_CONSTANT(KEY_DIRECTION);
  BIND_CONSTANT(KEY_CYCLEWINDOWS);
  BIND_CONSTANT(KEY_MAIL);
  BIND_CONSTANT(KEY_BOOKMARKS);
  BIND_CONSTANT(KEY_COMPUTER);
  BIND_CONSTANT(KEY_BACK);
  BIND_CONSTANT(KEY_FORWARD);
  BIND_CONSTANT(KEY_CLOSECD);
  BIND_CONSTANT(KEY_EJECTCD);
  BIND_CONSTANT(KEY_EJECTCLOSECD);
  BIND_CONSTANT(KEY_NEXTSONG);
  BIND_CONSTANT(KEY_PLAYPAUSE);
  BIND_CONSTANT(KEY_PREVIOUSSONG);
  BIND_CONSTANT(KEY_STOPCD);
  BIND_CONSTANT(KEY_RECORD);
  BIND_CONSTANT(KEY_REWIND);
  BIND_CONSTANT(KEY_PHONE);
  BIND_CONSTANT(KEY_ISO);
  BIND_CONSTANT(KEY_CONFIG);
  BIND_CONSTANT(KEY_HOMEPAGE);
  BIND_CONSTANT(KEY_REFRESH);
  BIND_CONSTANT(KEY_EXIT);
  BIND_CONSTANT(KEY_MOVE);
  BIND_CONSTANT(KEY_EDIT);
  BIND_CONSTANT(KEY_SCROLLUP);
  BIND_CONSTANT(KEY_SCROLLDOWN);
  BIND_CONSTANT(KEY_KPLEFTPAREN);
  BIND_CONSTANT(KEY_KPRIGHTPAREN);
  BIND_CONSTANT(KEY_NEW);
  BIND_CONSTANT(KEY_REDO);
  BIND_CONSTANT(KEY_F13);
  BIND_CONSTANT(KEY_F14);
  BIND_CONSTANT(KEY_F15);
  BIND_CONSTANT(KEY_F16);
  BIND_CONSTANT(KEY_F17);
  BIND_CONSTANT(KEY_F18);
  BIND_CONSTANT(KEY_F19);
  BIND_CONSTANT(KEY_F20);
  BIND_CONSTANT(KEY_F21);
  BIND_CONSTANT(KEY_F22);
  BIND_CONSTANT(KEY_F23);
  BIND_CONSTANT(KEY_F24);
  BIND_CONSTANT(KEY_PLAYCD);
  BIND_CONSTANT(KEY_PAUSECD);
  BIND_CONSTANT(KEY_PROG3);
  BIND_CONSTANT(KEY_PROG4);
  BIND_CONSTANT(KEY_ALL_APPLICATIONS);
  BIND_CONSTANT(KEY_DASHBOARD);
  BIND_CONSTANT(KEY_SUSPEND);
  BIND_CONSTANT(KEY_CLOSE);
  BIND_CONSTANT(KEY_PLAY);
  BIND_CONSTANT(KEY_FASTFORWARD);
  BIND_CONSTANT(KEY_BASSBOOST);
  BIND_CONSTANT(KEY_PRINT);
  BIND_CONSTANT(KEY_HP);
  BIND_CONSTANT(KEY_CAMERA);
  BIND_CONSTANT(KEY_SOUND);
  BIND_CONSTANT(KEY_QUESTION);
  BIND_CONSTANT(KEY_EMAIL);
  BIND_CONSTANT(KEY_CHAT);
  BIND_CONSTANT(KEY_SEARCH);
  BIND_CONSTANT(KEY_CONNECT);
  BIND_CONSTANT(KEY_FINANCE);
  BIND_CONSTANT(KEY_SPORT);
  BIND_CONSTANT(KEY_SHOP);
  BIND_CONSTANT(KEY_ALTERASE);
  BIND_CONSTANT(KEY_CANCEL);
  BIND_CONSTANT(KEY_BRIGHTNESSDOWN);
  BIND_CONSTANT(KEY_BRIGHTNESSUP);
  BIND_CONSTANT(KEY_MEDIA);
  BIND_CONSTANT(KEY_SWITCHVIDEOMODE);
  BIND_CONSTANT(KEY_KBDILLUMTOGGLE);
  BIND_CONSTANT(KEY_KBDILLUMDOWN);
  BIND_CONSTANT(KEY_KBDILLUMUP);
  BIND_CONSTANT(KEY_SEND);
  BIND_CONSTANT(KEY_REPLY);
  BIND_CONSTANT(KEY_FORWARDMAIL);
  BIND_CONSTANT(KEY_SAVE);
  BIND_CONSTANT(KEY_DOCUMENTS);
  BIND_CONSTANT(KEY_BATTERY);
  BIND_CONSTANT(KEY_BLUETOOTH);
  BIND_CONSTANT(KEY_WLAN);
  BIND_CONSTANT(KEY_UWB);
  BIND_CONSTANT(KEY_UNKNOWN);
  BIND_CONSTANT(KEY_VIDEO_NEXT);
  BIND_CONSTANT(KEY_VIDEO_PREV);
  BIND_CONSTANT(KEY_BRIGHTNESS_CYCLE);
  BIND_CONSTANT(KEY_BRIGHTNESS_AUTO);
  BIND_CONSTANT(KEY_BRIGHTNESS_ZERO);
  BIND_CONSTANT(KEY_DISPLAY_OFF);
  BIND_CONSTANT(KEY_WWAN);
  BIND_CONSTANT(KEY_WIMAX);
  BIND_CONSTANT(KEY_RFKILL);
  BIND_CONSTANT(KEY_MICMUTE);
  BIND_CONSTANT(BTN_MISC);
  BIND_CONSTANT(BTN_0);
  BIND_CONSTANT(BTN_1);
  BIND_CONSTANT(BTN_2);
  BIND_CONSTANT(BTN_3);
  BIND_CONSTANT(BTN_4);
  BIND_CONSTANT(BTN_5);
  BIND_CONSTANT(BTN_6);
  BIND_CONSTANT(BTN_7);
  BIND_CONSTANT(BTN_8);
  BIND_CONSTANT(BTN_9);
  BIND_CONSTANT(BTN_MOUSE);
  BIND_CONSTANT(BTN_LEFT);
  BIND_CONSTANT(BTN_RIGHT);
  BIND_CONSTANT(BTN_MIDDLE);
  BIND_CONSTANT(BTN_SIDE);
  BIND_CONSTANT(BTN_EXTRA);
  BIND_CONSTANT(BTN_FORWARD);
  BIND_CONSTANT(BTN_BACK);
  BIND_CONSTANT(BTN_TASK);
  BIND_CONSTANT(BTN_JOYSTICK);
  BIND_CONSTANT(BTN_TRIGGER);
  BIND_CONSTANT(BTN_THUMB);
  BIND_CONSTANT(BTN_THUMB2);
  BIND_CONSTANT(BTN_TOP);
  BIND_CONSTANT(BTN_TOP2);
  BIND_CONSTANT(BTN_PINKIE);
  BIND_CONSTANT(BTN_BASE);
  BIND_CONSTANT(BTN_BASE2);
  BIND_CONSTANT(BTN_BASE3);
  BIND_CONSTANT(BTN_BASE4);
  BIND_CONSTANT(BTN_BASE5);
  BIND_CONSTANT(BTN_BASE6);
  BIND_CONSTANT(BTN_DEAD);
  BIND_CONSTANT(BTN_GAMEPAD);
  BIND_CONSTANT(BTN_SOUTH);
  BIND_CONSTANT(BTN_A);
  BIND_CONSTANT(BTN_EAST);
  BIND_CONSTANT(BTN_B);
  BIND_CONSTANT(BTN_C);
  BIND_CONSTANT(BTN_NORTH);
  BIND_CONSTANT(BTN_X);
  BIND_CONSTANT(BTN_WEST);
  BIND_CONSTANT(BTN_Y);
  BIND_CONSTANT(BTN_Z);
  BIND_CONSTANT(BTN_TL);
  BIND_CONSTANT(BTN_TR);
  BIND_CONSTANT(BTN_TL2);
  BIND_CONSTANT(BTN_TR2);
  BIND_CONSTANT(BTN_SELECT);
  BIND_CONSTANT(BTN_START);
  BIND_CONSTANT(BTN_MODE);
  BIND_CONSTANT(BTN_THUMBL);
  BIND_CONSTANT(BTN_THUMBR);
  BIND_CONSTANT(BTN_DIGI);
  BIND_CONSTANT(BTN_TOOL_PEN);
  BIND_CONSTANT(BTN_TOOL_RUBBER);
  BIND_CONSTANT(BTN_TOOL_BRUSH);
  BIND_CONSTANT(BTN_TOOL_PENCIL);
  BIND_CONSTANT(BTN_TOOL_AIRBRUSH);
  BIND_CONSTANT(BTN_TOOL_FINGER);
  BIND_CONSTANT(BTN_TOOL_MOUSE);
  BIND_CONSTANT(BTN_TOOL_LENS);
  BIND_CONSTANT(BTN_TOOL_QUINTTAP);
  BIND_CONSTANT(BTN_STYLUS3);
  BIND_CONSTANT(BTN_TOUCH);
  BIND_CONSTANT(BTN_STYLUS);
  BIND_CONSTANT(BTN_STYLUS2);
  BIND_CONSTANT(BTN_TOOL_DOUBLETAP);
  BIND_CONSTANT(BTN_TOOL_TRIPLETAP);
  BIND_CONSTANT(BTN_TOOL_QUADTAP);
  BIND_CONSTANT(BTN_WHEEL);
  BIND_CONSTANT(BTN_GEAR_DOWN);
  BIND_CONSTANT(BTN_GEAR_UP);
  BIND_CONSTANT(KEY_OK);
  BIND_CONSTANT(KEY_SELECT);
  BIND_CONSTANT(KEY_GOTO);
  BIND_CONSTANT(KEY_CLEAR);
  BIND_CONSTANT(KEY_POWER2);
  BIND_CONSTANT(KEY_OPTION);
  BIND_CONSTANT(KEY_INFO);
  BIND_CONSTANT(KEY_TIME);
  BIND_CONSTANT(KEY_VENDOR);
  BIND_CONSTANT(KEY_ARCHIVE);
  BIND_CONSTANT(KEY_PROGRAM);
  BIND_CONSTANT(KEY_CHANNEL);
  BIND_CONSTANT(KEY_FAVORITES);
  BIND_CONSTANT(KEY_EPG);
  BIND_CONSTANT(KEY_PVR);
  BIND_CONSTANT(KEY_MHP);
  BIND_CONSTANT(KEY_LANGUAGE);
  BIND_CONSTANT(KEY_TITLE);
  BIND_CONSTANT(KEY_SUBTITLE);
  BIND_CONSTANT(KEY_ANGLE);
  BIND_CONSTANT(KEY_FULL_SCREEN);
  BIND_CONSTANT(KEY_ZOOM);
  BIND_CONSTANT(KEY_MODE);
  BIND_CONSTANT(KEY_KEYBOARD);
  BIND_CONSTANT(KEY_ASPECT_RATIO);
  BIND_CONSTANT(KEY_SCREEN);
  BIND_CONSTANT(KEY_PC);
  BIND_CONSTANT(KEY_TV);
  BIND_CONSTANT(KEY_TV2);
  BIND_CONSTANT(KEY_VCR);
  BIND_CONSTANT(KEY_VCR2);
  BIND_CONSTANT(KEY_SAT);
  BIND_CONSTANT(KEY_SAT2);
  BIND_CONSTANT(KEY_CD);
  BIND_CONSTANT(KEY_TAPE);
  BIND_CONSTANT(KEY_RADIO);
  BIND_CONSTANT(KEY_TUNER);
  BIND_CONSTANT(KEY_PLAYER);
  BIND_CONSTANT(KEY_TEXT);
  BIND_CONSTANT(KEY_DVD);
  BIND_CONSTANT(KEY_AUX);
  BIND_CONSTANT(KEY_MP3);
  BIND_CONSTANT(KEY_AUDIO);
  BIND_CONSTANT(KEY_VIDEO);
  BIND_CONSTANT(KEY_DIRECTORY);
  BIND_CONSTANT(KEY_LIST);
  BIND_CONSTANT(KEY_MEMO);
  BIND_CONSTANT(KEY_CALENDAR);
  BIND_CONSTANT(KEY_RED);
  BIND_CONSTANT(KEY_GREEN);
  BIND_CONSTANT(KEY_YELLOW);
  BIND_CONSTANT(KEY_BLUE);
  BIND_CONSTANT(KEY_CHANNELUP);
  BIND_CONSTANT(KEY_CHANNELDOWN);
  BIND_CONSTANT(KEY_FIRST);
  BIND_CONSTANT(KEY_LAST);
  BIND_CONSTANT(KEY_AB);
  BIND_CONSTANT(KEY_NEXT);
  BIND_CONSTANT(KEY_RESTART);
  BIND_CONSTANT(KEY_SLOW);
  BIND_CONSTANT(KEY_SHUFFLE);
  BIND_CONSTANT(KEY_BREAK);
  BIND_CONSTANT(KEY_PREVIOUS);
  BIND_CONSTANT(KEY_DIGITS);
  BIND_CONSTANT(KEY_TEEN);
  BIND_CONSTANT(KEY_TWEN);
  BIND_CONSTANT(KEY_VIDEOPHONE);
  BIND_CONSTANT(KEY_GAMES);
  BIND_CONSTANT(KEY_ZOOMIN);
  BIND_CONSTANT(KEY_ZOOMOUT);
  BIND_CONSTANT(KEY_ZOOMRESET);
  BIND_CONSTANT(KEY_WORDPROCESSOR);
  BIND_CONSTANT(KEY_EDITOR);
  BIND_CONSTANT(KEY_SPREADSHEET);
  BIND_CONSTANT(KEY_GRAPHICSEDITOR);
  BIND_CONSTANT(KEY_PRESENTATION);
  BIND_CONSTANT(KEY_DATABASE);
  BIND_CONSTANT(KEY_NEWS);
  BIND_CONSTANT(KEY_VOICEMAIL);
  BIND_CONSTANT(KEY_ADDRESSBOOK);
  BIND_CONSTANT(KEY_MESSENGER);
  BIND_CONSTANT(KEY_DISPLAYTOGGLE);
  BIND_CONSTANT(KEY_BRIGHTNESS_TOGGLE);
  BIND_CONSTANT(KEY_SPELLCHECK);
  BIND_CONSTANT(KEY_LOGOFF);
  BIND_CONSTANT(KEY_DOLLAR);
  BIND_CONSTANT(KEY_EURO);
  BIND_CONSTANT(KEY_FRAMEBACK);
  BIND_CONSTANT(KEY_FRAMEFORWARD);
  BIND_CONSTANT(KEY_CONTEXT_MENU);
  BIND_CONSTANT(KEY_MEDIA_REPEAT);
  BIND_CONSTANT(KEY_10CHANNELSUP);
  BIND_CONSTANT(KEY_10CHANNELSDOWN);
  BIND_CONSTANT(KEY_IMAGES);
  BIND_CONSTANT(KEY_NOTIFICATION_CENTER);
  BIND_CONSTANT(KEY_PICKUP_PHONE);
  BIND_CONSTANT(KEY_HANGUP_PHONE);
  BIND_CONSTANT(KEY_DEL_EOL);
  BIND_CONSTANT(KEY_DEL_EOS);
  BIND_CONSTANT(KEY_INS_LINE);
  BIND_CONSTANT(KEY_DEL_LINE);
  BIND_CONSTANT(KEY_FN);
  BIND_CONSTANT(KEY_FN_ESC);
  BIND_CONSTANT(KEY_FN_F1);
  BIND_CONSTANT(KEY_FN_F2);
  BIND_CONSTANT(KEY_FN_F3);
  BIND_CONSTANT(KEY_FN_F4);
  BIND_CONSTANT(KEY_FN_F5);
  BIND_CONSTANT(KEY_FN_F6);
  BIND_CONSTANT(KEY_FN_F7);
  BIND_CONSTANT(KEY_FN_F8);
  BIND_CONSTANT(KEY_FN_F9);
  BIND_CONSTANT(KEY_FN_F10);
  BIND_CONSTANT(KEY_FN_F11);
  BIND_CONSTANT(KEY_FN_F12);
  BIND_CONSTANT(KEY_FN_1);
  BIND_CONSTANT(KEY_FN_2);
  BIND_CONSTANT(KEY_FN_D);
  BIND_CONSTANT(KEY_FN_E);
  BIND_CONSTANT(KEY_FN_F);
  BIND_CONSTANT(KEY_FN_S);
  BIND_CONSTANT(KEY_FN_B);
  BIND_CONSTANT(KEY_FN_RIGHT_SHIFT);
  BIND_CONSTANT(KEY_BRL_DOT1);
  BIND_CONSTANT(KEY_BRL_DOT2);
  BIND_CONSTANT(KEY_BRL_DOT3);
  BIND_CONSTANT(KEY_BRL_DOT4);
  BIND_CONSTANT(KEY_BRL_DOT5);
  BIND_CONSTANT(KEY_BRL_DOT6);
  BIND_CONSTANT(KEY_BRL_DOT7);
  BIND_CONSTANT(KEY_BRL_DOT8);
  BIND_CONSTANT(KEY_BRL_DOT9);
  BIND_CONSTANT(KEY_BRL_DOT10);
  BIND_CONSTANT(KEY_NUMERIC_0);
  BIND_CONSTANT(KEY_NUMERIC_1);
  BIND_CONSTANT(KEY_NUMERIC_2);
  BIND_CONSTANT(KEY_NUMERIC_3);
  BIND_CONSTANT(KEY_NUMERIC_4);
  BIND_CONSTANT(KEY_NUMERIC_5);
  BIND_CONSTANT(KEY_NUMERIC_6);
  BIND_CONSTANT(KEY_NUMERIC_7);
  BIND_CONSTANT(KEY_NUMERIC_8);
  BIND_CONSTANT(KEY_NUMERIC_9);
  BIND_CONSTANT(KEY_NUMERIC_STAR);
  BIND_CONSTANT(KEY_NUMERIC_POUND);
  BIND_CONSTANT(KEY_NUMERIC_A);
  BIND_CONSTANT(KEY_NUMERIC_B);
  BIND_CONSTANT(KEY_NUMERIC_C);
  BIND_CONSTANT(KEY_NUMERIC_D);
  BIND_CONSTANT(KEY_CAMERA_FOCUS);
  BIND_CONSTANT(KEY_WPS_BUTTON);
  BIND_CONSTANT(KEY_TOUCHPAD_TOGGLE);
  BIND_CONSTANT(KEY_TOUCHPAD_ON);
  BIND_CONSTANT(KEY_TOUCHPAD_OFF);
  BIND_CONSTANT(KEY_CAMERA_ZOOMIN);
  BIND_CONSTANT(KEY_CAMERA_ZOOMOUT);
  BIND_CONSTANT(KEY_CAMERA_UP);
  BIND_CONSTANT(KEY_CAMERA_DOWN);
  BIND_CONSTANT(KEY_CAMERA_LEFT);
  BIND_CONSTANT(KEY_CAMERA_RIGHT);
  BIND_CONSTANT(KEY_ATTENDANT_ON);
  BIND_CONSTANT(KEY_ATTENDANT_OFF);
  BIND_CONSTANT(KEY_ATTENDANT_TOGGLE);
  BIND_CONSTANT(KEY_LIGHTS_TOGGLE);
  BIND_CONSTANT(BTN_DPAD_UP);
  BIND_CONSTANT(BTN_DPAD_DOWN);
  BIND_CONSTANT(BTN_DPAD_LEFT);
  BIND_CONSTANT(BTN_DPAD_RIGHT);
  BIND_CONSTANT(KEY_ALS_TOGGLE);
  BIND_CONSTANT(KEY_ROTATE_LOCK_TOGGLE);
  BIND_CONSTANT(KEY_BUTTONCONFIG);
  BIND_CONSTANT(KEY_TASKMANAGER);
  BIND_CONSTANT(KEY_JOURNAL);
  BIND_CONSTANT(KEY_CONTROLPANEL);
  BIND_CONSTANT(KEY_APPSELECT);
  BIND_CONSTANT(KEY_SCREENSAVER);
  BIND_CONSTANT(KEY_VOICECOMMAND);
  BIND_CONSTANT(KEY_ASSISTANT);
  BIND_CONSTANT(KEY_KBD_LAYOUT_NEXT);
  BIND_CONSTANT(KEY_EMOJI_PICKER);
  BIND_CONSTANT(KEY_DICTATE);
  BIND_CONSTANT(KEY_BRIGHTNESS_MIN);
  BIND_CONSTANT(KEY_BRIGHTNESS_MAX);
  BIND_CONSTANT(KEY_KBDINPUTASSIST_PREV);
  BIND_CONSTANT(KEY_KBDINPUTASSIST_NEXT);
  BIND_CONSTANT(KEY_KBDINPUTASSIST_PREVGROUP);
  BIND_CONSTANT(KEY_KBDINPUTASSIST_NEXTGROUP);
  BIND_CONSTANT(KEY_KBDINPUTASSIST_ACCEPT);
  BIND_CONSTANT(KEY_KBDINPUTASSIST_CANCEL);
  BIND_CONSTANT(KEY_RIGHT_UP);
  BIND_CONSTANT(KEY_RIGHT_DOWN);
  BIND_CONSTANT(KEY_LEFT_UP);
  BIND_CONSTANT(KEY_LEFT_DOWN);
  BIND_CONSTANT(KEY_ROOT_MENU);
  BIND_CONSTANT(KEY_MEDIA_TOP_MENU);
  BIND_CONSTANT(KEY_NUMERIC_11);
  BIND_CONSTANT(KEY_NUMERIC_12);
  BIND_CONSTANT(KEY_AUDIO_DESC);
  BIND_CONSTANT(KEY_3D_MODE);
  BIND_CONSTANT(KEY_NEXT_FAVORITE);
  BIND_CONSTANT(KEY_STOP_RECORD);
  BIND_CONSTANT(KEY_PAUSE_RECORD);
  BIND_CONSTANT(KEY_VOD);
  BIND_CONSTANT(KEY_UNMUTE);
  BIND_CONSTANT(KEY_FASTREVERSE);
  BIND_CONSTANT(KEY_SLOWREVERSE);
  BIND_CONSTANT(KEY_DATA);
  BIND_CONSTANT(KEY_ONSCREEN_KEYBOARD);
  BIND_CONSTANT(KEY_PRIVACY_SCREEN_TOGGLE);
  BIND_CONSTANT(KEY_SELECTIVE_SCREENSHOT);
  BIND_CONSTANT(KEY_NEXT_ELEMENT);
  BIND_CONSTANT(KEY_PREVIOUS_ELEMENT);
  BIND_CONSTANT(KEY_AUTOPILOT_ENGAGE_TOGGLE);
  BIND_CONSTANT(KEY_MARK_WAYPOINT);
  BIND_CONSTANT(KEY_SOS);
  BIND_CONSTANT(KEY_NAV_CHART);
  BIND_CONSTANT(KEY_FISHING_CHART);
  BIND_CONSTANT(KEY_SINGLE_RANGE_RADAR);
  BIND_CONSTANT(KEY_DUAL_RANGE_RADAR);
  BIND_CONSTANT(KEY_RADAR_OVERLAY);
  BIND_CONSTANT(KEY_TRADITIONAL_SONAR);
  BIND_CONSTANT(KEY_CLEARVU_SONAR);
  BIND_CONSTANT(KEY_SIDEVU_SONAR);
  BIND_CONSTANT(KEY_NAV_INFO);
  BIND_CONSTANT(KEY_BRIGHTNESS_MENU);
  BIND_CONSTANT(KEY_MACRO1);
  BIND_CONSTANT(KEY_MACRO2);
  BIND_CONSTANT(KEY_MACRO3);
  BIND_CONSTANT(KEY_MACRO4);
  BIND_CONSTANT(KEY_MACRO5);
  BIND_CONSTANT(KEY_MACRO6);
  BIND_CONSTANT(KEY_MACRO7);
  BIND_CONSTANT(KEY_MACRO8);
  BIND_CONSTANT(KEY_MACRO9);
  BIND_CONSTANT(KEY_MACRO10);
  BIND_CONSTANT(KEY_MACRO11);
  BIND_CONSTANT(KEY_MACRO12);
  BIND_CONSTANT(KEY_MACRO13);
  BIND_CONSTANT(KEY_MACRO14);
  BIND_CONSTANT(KEY_MACRO15);
  BIND_CONSTANT(KEY_MACRO16);
  BIND_CONSTANT(KEY_MACRO17);
  BIND_CONSTANT(KEY_MACRO18);
  BIND_CONSTANT(KEY_MACRO19);
  BIND_CONSTANT(KEY_MACRO20);
  BIND_CONSTANT(KEY_MACRO21);
  BIND_CONSTANT(KEY_MACRO22);
  BIND_CONSTANT(KEY_MACRO23);
  BIND_CONSTANT(KEY_MACRO24);
  BIND_CONSTANT(KEY_MACRO25);
  BIND_CONSTANT(KEY_MACRO26);
  BIND_CONSTANT(KEY_MACRO27);
  BIND_CONSTANT(KEY_MACRO28);
  BIND_CONSTANT(KEY_MACRO29);
  BIND_CONSTANT(KEY_MACRO30);
  BIND_CONSTANT(KEY_MACRO_RECORD_START);
  BIND_CONSTANT(KEY_MACRO_RECORD_STOP);
  BIND_CONSTANT(KEY_MACRO_PRESET_CYCLE);
  BIND_CONSTANT(KEY_MACRO_PRESET1);
  BIND_CONSTANT(KEY_MACRO_PRESET2);
  BIND_CONSTANT(KEY_MACRO_PRESET3);
  BIND_CONSTANT(KEY_KBD_LCD_MENU1);
  BIND_CONSTANT(KEY_KBD_LCD_MENU2);
  BIND_CONSTANT(KEY_KBD_LCD_MENU3);
  BIND_CONSTANT(KEY_KBD_LCD_MENU4);
  BIND_CONSTANT(KEY_KBD_LCD_MENU5);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY1);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY2);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY3);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY4);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY5);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY6);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY7);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY8);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY9);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY10);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY11);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY12);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY13);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY14);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY15);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY16);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY17);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY18);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY19);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY20);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY21);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY22);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY23);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY24);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY25);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY26);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY27);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY28);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY29);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY30);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY31);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY32);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY33);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY34);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY35);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY36);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY37);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY38);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY39);
  BIND_CONSTANT(BTN_TRIGGER_HAPPY40);
  BIND_CONSTANT(KEY_MIN_INTERESTING);
  BIND_CONSTANT(KEY_MAX);
  BIND_CONSTANT(KEY_CNT);
  BIND_CONSTANT(REL_X);
  BIND_CONSTANT(REL_Y);
  BIND_CONSTANT(REL_Z);
  BIND_CONSTANT(REL_RX);
  BIND_CONSTANT(REL_RY);
  BIND_CONSTANT(REL_RZ);
  BIND_CONSTANT(REL_HWHEEL);
  BIND_CONSTANT(REL_DIAL);
  BIND_CONSTANT(REL_WHEEL);
  BIND_CONSTANT(REL_MISC);
  BIND_CONSTANT(REL_RESERVED);
  BIND_CONSTANT(REL_WHEEL_HI_RES);
  BIND_CONSTANT(REL_HWHEEL_HI_RES);
  BIND_CONSTANT(REL_MAX);
  BIND_CONSTANT(REL_CNT);
  BIND_CONSTANT(ABS_X);
  BIND_CONSTANT(ABS_Y);
  BIND_CONSTANT(ABS_Z);
  BIND_CONSTANT(ABS_RX);
  BIND_CONSTANT(ABS_RY);
  BIND_CONSTANT(ABS_RZ);
  BIND_CONSTANT(ABS_THROTTLE);
  BIND_CONSTANT(ABS_RUDDER);
  BIND_CONSTANT(ABS_WHEEL);
  BIND_CONSTANT(ABS_GAS);
  BIND_CONSTANT(ABS_BRAKE);
  BIND_CONSTANT(ABS_HAT0X);
  BIND_CONSTANT(ABS_HAT0Y);
  BIND_CONSTANT(ABS_HAT1X);
  BIND_CONSTANT(ABS_HAT1Y);
  BIND_CONSTANT(ABS_HAT2X);
  BIND_CONSTANT(ABS_HAT2Y);
  BIND_CONSTANT(ABS_HAT3X);
  BIND_CONSTANT(ABS_HAT3Y);
  BIND_CONSTANT(ABS_PRESSURE);
  BIND_CONSTANT(ABS_DISTANCE);
  BIND_CONSTANT(ABS_TILT_X);
  BIND_CONSTANT(ABS_TILT_Y);
  BIND_CONSTANT(ABS_TOOL_WIDTH);
  BIND_CONSTANT(ABS_VOLUME);
  BIND_CONSTANT(ABS_MISC);
  BIND_CONSTANT(ABS_RESERVED);
  BIND_CONSTANT(ABS_MT_SLOT);
  BIND_CONSTANT(ABS_MT_TOUCH_MAJOR);
  BIND_CONSTANT(ABS_MT_TOUCH_MINOR);
  BIND_CONSTANT(ABS_MT_WIDTH_MAJOR);
  BIND_CONSTANT(ABS_MT_WIDTH_MINOR);
  BIND_CONSTANT(ABS_MT_ORIENTATION);
  BIND_CONSTANT(ABS_MT_POSITION_X);
  BIND_CONSTANT(ABS_MT_POSITION_Y);
  BIND_CONSTANT(ABS_MT_TOOL_TYPE);
  BIND_CONSTANT(ABS_MT_BLOB_ID);
  BIND_CONSTANT(ABS_MT_TRACKING_ID);
  BIND_CONSTANT(ABS_MT_PRESSURE);
  BIND_CONSTANT(ABS_MT_DISTANCE);
  BIND_CONSTANT(ABS_MT_TOOL_X);
  BIND_CONSTANT(ABS_MT_TOOL_Y);
  BIND_CONSTANT(ABS_MAX);
  BIND_CONSTANT(ABS_CNT);
  BIND_CONSTANT(SW_LID);
  BIND_CONSTANT(SW_TABLET_MODE);
  BIND_CONSTANT(SW_HEADPHONE_INSERT);
  BIND_CONSTANT(SW_RFKILL_ALL);
  BIND_CONSTANT(SW_RADIO);
  BIND_CONSTANT(SW_MICROPHONE_INSERT);
  BIND_CONSTANT(SW_DOCK);
  BIND_CONSTANT(SW_LINEOUT_INSERT);
  BIND_CONSTANT(SW_JACK_PHYSICAL_INSERT);
  BIND_CONSTANT(SW_VIDEOOUT_INSERT);
  BIND_CONSTANT(SW_CAMERA_LENS_COVER);
  BIND_CONSTANT(SW_KEYPAD_SLIDE);
  BIND_CONSTANT(SW_FRONT_PROXIMITY);
  BIND_CONSTANT(SW_ROTATE_LOCK);
  BIND_CONSTANT(SW_LINEIN_INSERT);
  BIND_CONSTANT(SW_MUTE_DEVICE);
  BIND_CONSTANT(SW_PEN_INSERTED);
  BIND_CONSTANT(SW_MACHINE_COVER);
  BIND_CONSTANT(SW_MAX);
  BIND_CONSTANT(SW_CNT);
  BIND_CONSTANT(MSC_SERIAL);
  BIND_CONSTANT(MSC_PULSELED);
  BIND_CONSTANT(MSC_GESTURE);
  BIND_CONSTANT(MSC_RAW);
  BIND_CONSTANT(MSC_SCAN);
  BIND_CONSTANT(MSC_TIMESTAMP);
  BIND_CONSTANT(MSC_MAX);
  BIND_CONSTANT(MSC_CNT);
  BIND_CONSTANT(LED_NUML);
  BIND_CONSTANT(LED_CAPSL);
  BIND_CONSTANT(LED_SCROLLL);
  BIND_CONSTANT(LED_COMPOSE);
  BIND_CONSTANT(LED_KANA);
  BIND_CONSTANT(LED_SLEEP);
  BIND_CONSTANT(LED_SUSPEND);
  BIND_CONSTANT(LED_MUTE);
  BIND_CONSTANT(LED_MISC);
  BIND_CONSTANT(LED_MAIL);
  BIND_CONSTANT(LED_CHARGING);
  BIND_CONSTANT(LED_MAX);
  BIND_CONSTANT(LED_CNT);
  BIND_CONSTANT(REP_DELAY);
  BIND_CONSTANT(REP_PERIOD);
  BIND_CONSTANT(REP_MAX);
  BIND_CONSTANT(REP_CNT);
  BIND_CONSTANT(SND_CLICK);
  BIND_CONSTANT(SND_BELL);
  BIND_CONSTANT(SND_TONE);
  BIND_CONSTANT(SND_MAX);
  BIND_CONSTANT(SND_CNT);
};
} // namespace evdev
