nav:
  - ./APUDatabase.md
  - ./APUEntry.md
  - ./ActionStartInputPlumber.md
  - ./ActionStartPowerStation.md
  - ./ActionTurboTakeover.md
  - ./AppLifecycleHook.md
  - ./AudioManager.md
  - ./BackInputHandler.md
  - ./BehaviorNode.md
  - ./Bitwise.md
  - ./BlockDevice.md
  - ./BluetoothAdapter.md
  - ./BluetoothDevice.md
  - ./BluetoothManager.md
  - ./BluezInstance.md
  - ./BoxArtManager.md
  - ./BoxArtProvider.md
  - ./CPU.md
  - ./CPUCore.md
  - ./Cache.md
  - ./CardButton.md
  - ./CardButtonSetting.md
  - ./CardIconButton.md
  - ./CardInputIconButton.md
  - ./CardMappingButton.md
  - ./CardMappingButtonGroup.md
  - ./Command.md
  - ./ComponentTextInput.md
  - ./CompositeDevice.md
  - ./Cpu.md
  - ./CpuCore.md
  - ./CustomLogger.md
  - ./DBusDevice.md
  - ./DRMCardInfo.md
  - ./DRMCardInfoAMD.md
  - ./DRMCardInfoIntel.md
  - ./DRMCardPort.md
  - ./Dialog.md
  - ./DiskManager.md
  - ./DisplayManager.md
  - ./DisplayManager.BacklightProvider.md
  - ./DisplayManager.BrightnessctlBacklight.md
  - ./DisplayManager.SteamOsBacklight.md
  - ./DriveCard.md
  - ./DriveDevice.md
  - ./Dropdown.md
  - ./Effect.md
  - ./EnhancedScrollContainer.md
  - ./EventDevice.md
  - ./ExpandableCard.md
  - ./FadeEffect.md
  - ./FifoReader.md
  - ./FilesystemDevice.md
  - ./FocusGroup.md
  - ./FocusGroupSetter.md
  - ./FocusManager.md
  - ./FocusSetter.md
  - ./FocusStack.md
  - ./GameCard.md
  - ./GamepadDevice.md
  - ./GamepadMapper.md
  - ./Gamescope.md
  - ./GamescopeInstance.md
  - ./GamescopeXWayland.md
  - ./GitHubClient.md
  - ./Gpu.md
  - ./GpuCard.md
  - ./GpuConnector.md
  - ./GrowerEffect.md
  - ./GutHookScript.md
  - ./GutStringUtils.md
  - ./GutTest.md
  - ./GutUtils.md
  - ./HTTPAPIClient.md
  - ./HTTPAPIClient.Response.md
  - ./HTTPImageFetcher.md
  - ./HandheldIconMapping.md
  - ./HandheldPlatform.md
  - ./HardwareManager.md
  - ./HardwareManager.GPUInfo.md
  - ./InputIcon.md
  - ./InputIconKeyboardMapping.md
  - ./InputIconManager.md
  - ./InputIconMapping.md
  - ./InputIconProcessor.md
  - ./InputManager.md
  - ./InputPlumber.md
  - ./InputPlumberAxisEvent.md
  - ./InputPlumberEvent.md
  - ./InputPlumberGamepadEvent.md
  - ./InputPlumberGyroEvent.md
  - ./InputPlumberInstance.md
  - ./InputPlumberMapping.md
  - ./InputPlumberMouseEvent.md
  - ./InputPlumberMouseMotionEvent.md
  - ./InputPlumberProfile.md
  - ./InputPlumberTouchEvent.md
  - ./InputPlumberTouchMotionEvent.md
  - ./InputPlumberTouchpadEvent.md
  - ./InputPlumberTriggerEvent.md
  - ./InputWatcher.md
  - ./InstallLocationCard.md
  - ./InstallLocationDialog.md
  - ./InstallManager.md
  - ./InstallManager.Request.md
  - ./InstallOptionDialog.md
  - ./InteractiveProcess.md
  - ./KeyboardContext.md
  - ./KeyboardDevice.md
  - ./KeyboardInstance.md
  - ./KeyboardKeyConfig.md
  - ./KeyboardLayout.md
  - ./KeyboardOpener.md
  - ./KeyboardRow.md
  - ./LaunchManager.md
  - ./Launcher.md
  - ./LevelIndicator.md
  - ./Library.md
  - ./Library.InstallLocation.md
  - ./Library.InstallOption.md
  - ./LibraryDeck.md
  - ./LibraryItem.md
  - ./LibraryLaunchItem.md
  - ./LibraryManager.md
  - ./LibraryRefreshState.md
  - ./LibraryRefresher.md
  - ./Log.md
  - ./LogManager.md
  - ./MangoApp.md
  - ./MouseDevice.md
  - ./MultiHTTPRequest.md
  - ./NetworkAccessPoint.md
  - ./NetworkActiveConnection.md
  - ./NetworkDevice.md
  - ./NetworkDeviceWireless.md
  - ./NetworkIpv4Config.md
  - ./NetworkManager.md
  - ./NetworkManagerInstance.md
  - ./NodeThread.md
  - ./Notification.md
  - ./NotificationContainer.md
  - ./NotificationManager.md
  - ./OSPlatform.md
  - ./OnScreenKeyboard.md
  - ./OverlayContainer.md
  - ./OverlayInputManager.md
  - ./OverlayProvider.md
  - ./PackageVerifier.md
  - ./PartitionCard.md
  - ./PartitionDevice.md
  - ./PerformanceManager.md
  - ./PerformanceProfile.md
  - ./PipeManager.md
  - ./Platform.md
  - ./Platform.OSInfo.md
  - ./PlatformAction.md
  - ./PlatformBazzite.md
  - ./PlatformChimeraOS.md
  - ./PlatformManjaro.md
  - ./PlatformNixOS.md
  - ./PlatformProvider.md
  - ./PlatformSteamOS.md
  - ./PlayAudioEffect.md
  - ./Plugin.md
  - ./PluginLoader.md
  - ./PluginManager.md
  - ./PowerManager.md
  - ./PowerSaver.md
  - ./PowerStation.md
  - ./PowerStationInstance.md
  - ./ProgressDialog.md
  - ./Pty.md
  - ./QuickBarCard.md
  - ./RaiseEffect.md
  - ./Reaper.md
  - ./ResourceProcessor.md
  - ./ResourceRegistry.md
  - ./RunningApp.md
  - ./Sandbox.md
  - ./SandboxBubblewrap.md
  - ./SandboxFirejail.md
  - ./ScrollerJoystick.md
  - ./SearchBar.md
  - ./SelectableText.md
  - ./SemanticVersion.md
  - ./SettingsManager.md
  - ./SharedThread.md
  - ./SharedThread.ExecutingTask.md
  - ./SharedThread.ScheduledTask.md
  - ./SlideEffect.md
  - ./SmoothScrollEffect.md
  - ./SoftwareUpdater.md
  - ./State.md
  - ./StateChanger.md
  - ./StateMachine.md
  - ./StateMachineWatcher.md
  - ./StateManager.md
  - ./StateUpdater.md
  - ./StateWatcher.md
  - ./StatesWatcher.md
  - ./StatusPanel.md
  - ./SteamRemovableMediaManager.md
  - ./Store.md
  - ./StoreItem.md
  - ./StoreItemDetails.md
  - ./StoreManager.md
  - ./SubReaper.md
  - ./TabContainerState.md
  - ./TabLabel.md
  - ./TabSetter.md
  - ./TabsHeader.md
  - ./TextSetter.md
  - ./ThemeSetter.md
  - ./ThemeUtils.md
  - ./ThreadGroup.md
  - ./ThreadPool.md
  - ./ThreadPool.Task.md
  - ./Toggle.md
  - ./Transition.md
  - ./TransitionContainer.md
  - ./UDisks2Instance.md
  - ./UPowerDevice.md
  - ./UPowerInstance.md
  - ./UUID.md
  - ./UserInterface.md
  - ./ValueSlider.md
  - ./Vdf.md
  - ./Version.md
  - ./VisibilityManager.md
  - ./WatchdogThread.md
  - ./WebsocketRPCClient.md
  - ./WifiNetworkTree.md
  - ./Xdg.md
