name: 🪲 Test

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run GUT tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          make in-docker IMAGE_TAG=4.6.1 TARGET='import docs dist test GAMESCOPE_CMD='

  build-x86_64:
    name: Run x86_64 build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          make in-docker TARGET='dist'

  build-aarch64:
    name: Run aarch64 build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          make in-docker TARGET='dist' TARGET_ARCH='aarch64'
